version: "3.9"
services:
  
    
  Achat:
    container_name: achat
    build: ./achat
    ports:
      - "8082:8082"   
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3306/achatdb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

    image: "achat"
    restart: unless-stopped
    depends_on:
      - db-mysql

  
  db-mysql:
      image: "mysql:5.6"
      container_name: db-mysql 
      environment:
        - MYSQL_ROOT_PASSWORD=root  #indisponsable pour la conteneurisation
        #- MYSQL_DATABASE=job
      volumes:
      - mysql-data:/var/lib/mysql  
      ports:
        - "3306:3306"
      restart: unless-stopped 

  
  